### ISSUE TITLE
Track Upstream Mothur Branch and Update Our Master Branch from That

### ISSUE THREAD

**Issue by azmfaridee** [azmfaridee/mothur#12]
Our code-base has been forked from [mothur](https://github.com/mothur/mothur) code-base. Since then there has been numerous commits in the _upstream_ but we have not been able to follow that up. This is because we are not _tracking_ the upstream branch in our code-base.

Follow the tutorial at http://help.github.com/fork-a-repo/ and add _upstream_ branch so that we can _track_ newest changes made by the core developers and and update our code from that.

**Comment by azmfaridee** [comment]
Here are some of the things that we need to do to _track_ the _upstream_ code:

```
$ git remote add upstream https://github.com/mothur/mothur.git
$ git fetch upstream
$ git merge upstream/master
```

I'm getting some conflict right now. Here are the details of the conflict.

```
Abu-Zahers-MacBook:mothur abuzaher$ git merge upstream/master
Auto-merging uchime_src/usort.cpp
Auto-merging uchime_src/uchime_main.cpp
Auto-merging uchime_src/uc.h
Auto-merging uchime_src/myutils.cpp
CONFLICT (content): Merge conflict in uchime_src/myutils.cpp
Auto-merging uchime_src/globalalign2.cpp
Auto-merging uchime_src/addtargets2.cpp
Removing phylodiversity.h
Removing phylodiversity.cpp
Auto-merging makefile
Auto-merging consensus.h
Auto-merging consensus.cpp
Removing bootstrapsharedcommand.h
Removing bootstrapsharedcommand.cpp
Auto-merging Mothur.xcodeproj/project.pbxproj
CONFLICT (content): Merge conflict in Mothur.xcodeproj/project.pbxproj
Automatic merge failed; fix conflicts and then commit the result.
```

I'm trying to fix it right now.

**Comment by mothur-westcott** [comment]
If you are going to do any development with Xcode 4, it has a really nice gui interface for merging and resolving conflicts with git repositories.

**Comment by azmfaridee** [comment]
@mothur-westcott Thanks for the tip, I'd be using Xcode 4.3 in Lion, so that would definitely help a lot.

I managed to fix the conflict and merge the upstream changes in [this commit](https://github.com/darthxaher/mothur/commit/9afd4008993a7f1c4aa9f90ea650617b21a52ffa).
