### ISSUE TITLE
Prepare Datasets for The Regularized Random Forest Algorithm

### ISSUE THREAD

**Issue by azmfaridee** [azmfaridee/mothur#2]
The current datasets that we have (for example [AmazonDatasets](http://www.mothur.org/w/images/3/37/AmazonData.zip)) does not contain much _Training Datasets_ with respect to the _Features_. We may have _Features_ of order of 100 or more whereas we have _Training Cases_ of only 10 to 20. This would not suffice for a proper training. Although _Random Forest_ is known for _Random Sampling_ by replacement for _Bootstrapping_ purpose, this is such a small ratio to being with.

@kdiverson: We were entertaining some idea about using _Classical_ ecology data like list of birds in an island which would give is the ratio that we've been looking for, but this _Classical_ data might be quite different from our _Microbial Ecology_ data. We were also considering investigating the use of _Artificial Microbial Community Ddatasets_. Can you provide me some of the links?

**Comment by mothur-westcott** [comment]
@kdiverson Would the dataset used in the SOP work? It's much larger than the AmazonData set and used in all the workshops.

**Comment by kdiverson** [comment]
The SOP dataset [0] would be good to use since that is the example used in the workshop. Other 16s datasets from HMP can be found here[1]. There are some mock datasets and real. In both cases there's a lot of metadata so these would be good for validating results. We could mask some of the metadata and see if the algorithm can correctly predict what metadata should be there. 

[0] http://www.mothur.org/wiki/Schloss_SOP
[1] http://www.hmpdacc.org/resources/dataset_documentation.php

**Comment by azmfaridee** [comment]
> The SOP dataset [0] would be good to use since that is the example used in the workshop. Other 16s datasets from HMP can be found here[1]. There are some mock datasets and real. In both cases there's a lot of metadata so these would be good for validating results. We could mask some of the metadata and see if the algorithm can correctly predict what metadata should be there. 
> 
> [0] http://www.mothur.org/wiki/Schloss_SOP
> [1] http://www.hmpdacc.org/resources/dataset_documentation.php

@kdiverson I've downloaded the datasets in [0], just trying to create the shared files with `make.shared` command.
However I'm not sure about [1], there are a lot of stuff in the link provided, so it would be better if you could clarify which one is most relevant to us.

**Comment by kdiverson** [comment]
@darthxaher we'll probably want to use 454 16s data. I'm not sure which is the best of those datasets. I'll have a look.

**Comment by kdiverson** [comment]
Another approach to dealing with minimal datasets is data augmentation. This is a process to take replicates of the data we do have and add noise to it. This should give us a more robust training set.

**Comment by azmfaridee** [comment]
@kdiverson Do you have any links to any research papers that demonstrates creating _large amount of artificial data from natural data as seed?_. I really like the idea, but I'd like to do proper research into this before I get my hands dirty, adding noise without knowing what we are doing would just worsen then training process.

**Comment by kdiverson** [comment]
@darthxaher yeah, it's in the Supervised classification of human microbiota paper.
