### ISSUE TITLE
Week 12 & 13: Continue Working in Mothur Code Integration

### ISSUE THREAD

**Issue by azmfaridee** [azmfaridee/mothur#23]
#### Weekly Update Issues: #3, #14, #15, #16, #17, #19,  #20 and #21

Continuing from last weeks task, we keep porting python code into C++. Major work would be a mock implementation of `classify.shared` command that can be called from mothur command line.

**Comment by kdiverson** [comment]
@darthxaher what's the timeline for the mothur integration? From the milestones it looks like this is to be finished in 11 days; is that still accurate? We might want to focus on getting the algo running in c++. Sarah and I can help with some of the housekeeping stuff if you want to work on optimizing the algo in c++.
