### ISSUE TITLE
Replace Normal Debug Messages in C++ implementation with MothurOut Code  

### ISSUE THREAD

**Issue by azmfaridee** [azmfaridee/mothur#28]
The file [macros.h](https://github.com/darthxaher/mothur/blob/master/fs/macros.h) has a lot of debugging macros defined, they are defined for standard cout, we need to make them work with mothur's MothurOut class

**Comment by azmfaridee** [comment]
Some macros like 

``` C
#define PRINT_VAR(X) (cout << #X << " -> " << X << endl)
```

are pretty difficult to convert to MothurOut code as as the macro uses _hash_ token to convert a variable's names to a string, we need to find alternate ways to implement this

**Comment by mothur-westcott** [comment]
The mothur.h header has several toString functions.  Can you use one of those? Something like: m->mothurOut(toString(X)); m->mothurOutEndLine();
